# Follower counts are approximate (Instagram, millions, ~2024) — the game
# only needs the relative ordering to be right.
data = [
    {"name": "Cristiano Ronaldo", "follower_count": 615, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 425, "description": "Musician and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 398, "description": "Media personality", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 396, "description": "Actor and wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Musician", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 364, "description": "Media personality", "country": "United States"},
    {"name": "Beyonce", "follower_count": 319, "description": "Musician", "country": "United States"},
    {"name": "Khloe Kardashian", "follower_count": 311, "description": "Media personality", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 294, "description": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 293, "description": "Model", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 283, "description": "Musician", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 269, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 252, "description": "Musician and actress", "country": "United States"},
    {"name": "Nicki Minaj", "follower_count": 229, "description": "Musician", "country": "Trinidad and Tobago"},
    {"name": "Neymar", "follower_count": 224, "description": "Footballer", "country": "Brazil"},
    {"name": "Kourtney Kardashian", "follower_count": 224, "description": "Media personality", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 213, "description": "Musician and actress", "country": "United States"},
    {"name": "Katy Perry", "follower_count": 207, "description": "Musician", "country": "United States"},
    {"name": "Zendaya", "follower_count": 184, "description": "Actress", "country": "United States"},
    {"name": "Kevin Hart", "follower_count": 179, "description": "Comedian and actor", "country": "United States"},
    {"name": "Cardi B", "follower_count": 165, "description": "Musician", "country": "United States"},
    {"name": "LeBron James", "follower_count": 159, "description": "Basketball player", "country": "United States"},
    {"name": "Demi Lovato", "follower_count": 156, "description": "Musician and actress", "country": "United States"},
    {"name": "Rihanna", "follower_count": 152, "description": "Musician and businesswoman", "country": "Barbados"},
    {"name": "Chris Brown", "follower_count": 144, "description": "Musician", "country": "United States"},
    {"name": "Drake", "follower_count": 143, "description": "Musician", "country": "Canada"},
    {"name": "Billie Eilish", "follower_count": 119, "description": "Musician", "country": "United States"},
    {"name": "Kylian Mbappe", "follower_count": 116, "description": "Footballer", "country": "France"},
    {"name": "Gigi Hadid", "follower_count": 79, "description": "Model", "country": "United States"},
    {"name": "Emma Watson", "follower_count": 75, "description": "Actress", "country": "United Kingdom"},
    {"name": "Shakira", "follower_count": 90, "description": "Musician", "country": "Colombia"},
    {"name": "Ellen DeGeneres", "follower_count": 136, "description": "Comedian and TV host", "country": "United States"},
    {"name": "Tom Holland", "follower_count": 68, "description": "Actor", "country": "United Kingdom"},
    {"name": "Keanu Reeves", "follower_count": 17, "description": "Actor", "country": "Canada"},
]
