# openTrivia DB json file

question_data = {
    "response_code": 0,
    "results": [
        {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
         "question": "The majority of Subaru vehicles are made in China.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Science: Computers",
         "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Books",
         "question": "The book 1984 was published in 1949.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "General Knowledge",
         "question": "The New York Subway is the oldest underground in the world.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "History",
         "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "In Team Fortress 2, the weapon &quot;Your Eternal Reward&quot; is a reference to the 1992 film Aladdin.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "General Knowledge",
         "question": "Nutella is produced by the German company Ferrero.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Sports",
         "question": "The Olympics tennis court is a giant green screen.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Music",
         "question": "John Williams composed the music for &quot;Star Wars&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]}
